version: '3.8'

services:
  auth-service:
    build:
      context: ./src/AuthService
      dockerfile: Dockerfile
    container_name: skybooker-auth-service
    restart: always
    networks:
      - skybooker-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  flight-service:
    build:
      context: ./src/FlightService
      dockerfile: Dockerfile
    container_name: skybooker-flight-service
    restart: always
    networks:
      - skybooker-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - auth-service

  booking-service:
    build:
      context: ./src/BookingService
      dockerfile: Dockerfile
    container_name: skybooker-booking-service
    restart: always
    networks:
      - skybooker-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - auth-service
      - flight-service

  gateway:
    build:
      context: ./src/Gateway
      dockerfile: Dockerfile
    container_name: skybooker-gateway
    restart: always
    ports:
      - "8080:80"
    networks:
      - skybooker-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - auth-service
      - flight-service
      - booking-service

  frontend:
    build:
      context: ./SkyBooker-frontend
      dockerfile: Dockerfile
    container_name: skybooker-frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - skybooker-network
    depends_on:
      - gateway

networks:
  skybooker-network:
    driver: bridge
